### ISSUE TITLE
February Meetup

### ISSUE THREAD

**Issue by paweldudek** [paweldudek/mobile-warsaw-organization#1]
- [x] Venue
- [x] Speakers
- [x] Sponsor
- [x] Updated mobile-warsaw.pl

Speaking: 
- Saul More
- Antoni Kędracki

Date: 24th February 2014

**Comment by wojtekerbetowski** [comment]
Data?

**Comment by paweldudek** [comment]
Dodane. ;)

**Comment by paweldudek** [comment]
Panowie, a nagrywanie? Nagrywamy to?

**Comment by wojtekerbetowski** [comment]
Pewnie, że warto nagrać. A jak z miejscem. Wyjaśniło się coś?
Mam jakby co chwilę, żeby odezwać się do knajp, ale nie wiem czy ktoś do jakiejś próbował już?

**Comment by paweldudek** [comment]
Póki co nie ruszaliśmy tematu. Chyba, ze Antek juz cos robił w tej sprawie. 

Ktos robił cos juz w Chmielna 25? Doszły mnie słuchy, ze spoko miejsce.

**Comment by potiuk** [comment]
Na streetview nie wygląda za dobrze ;)

https://www.google.pl/maps/preview/@52.232174,21.013802,3a,75y,155.38h,79.24t/data=!3m4!1e1!3m2!1s0lS0w63PEB3rqLYz77h_NQ!2e0!6m1!1e1

A tak serio to nie byłem :)

J.

*Jarek Potiuk, *CTO
*Polidea
http://www.polidea.pl/en/#utm_source=Email_Sig&utm_medium=email&utm_campaign=Email,
*
 Mobile Central Europe http://mobilecentraleurope.com/
Mobile: +48 660 796 129

2014-02-03 Pawel Dudek notifications@github.com:

**Comment by paweldudek** [comment]
Haha! :D no jak pogoda sie nie uda to moze byc kiepsko bez dachu nad głowa ;) 

Ale na serio - tam nowy budynek postawili. ;)

**Comment by wojtekerbetowski** [comment]
Mo¿emy nagraæ, muszê tylko w porê kamerê WJUG przechwyciæ.

2014-02-03 Pawel Dudek notifications@github.com:

> Haha! :D no jak pogoda sie nie uda to moze byc kiepsko bez dachu nad g³owa
> ;)
> 
> Ale na serio - tam nowy budynek postawili. ;)
> 
> > On 3 lut 2014, at 18:08, Jarek Potiuk notifications@github.com wrote:
> > 
> > Na streetview nie wygl±da za dobrze ;)
> > 
> > https://www.google.pl/maps/preview/@52.232174,21.013802,3a,75y,155.38h,79.24t/data=!3m4!1e1!3m2!1s0lS0w63PEB3rqLYz77h_NQ!2e0!6m1!1e1
> > 
> > A tak serio to nie by³em :)
> > 
> > J.
> > 
> > *Jarek Potiuk, *CTO
> > *Polidea
> > <
> > http://www.polidea.pl/en/#utm_source=Email_Sig&utm_medium=email&utm_campaign=Email>,
> > 
> > *
> > Mobile Central Europe http://mobilecentraleurope.com/
> > Mobile: +48 660 796 129
> > 
> > 2014-02-03 Pawel Dudek notifications@github.com:
> > 
> > > Póki co nie ruszali¶my tematu. Chyba, ze Antek juz cos robi³ w tej
> > > sprawie.
> > > 
> > > Ktos robi³ cos juz w Chmielna 25? Dosz³y mnie s³uchy, ze spoko
> > > miejsce.
> > > 
> > > > On 3 lut 2014, at 14:38, Wojciech Erbetowski <
> > > > notifications@github.com>
> > > > wrote:
> > > > 
> > > > Pewnie, ¿e warto nagraæ. A jak z miejscem. Wyja¶ni³o siê co¶?
> > > > Mam jakby co chwilê, ¿eby odezwaæ siê do knajp, ale nie wiem czy
> > > > kto¶ do
> > > > jakiej¶ próbowa³ ju¿?
> > > > 
> > > > ## 
> > > > 
> > > > Reply to this email directly or view it on GitHub.
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/paweldudek/mobile-warsaw-organization/issues/1#issuecomment-33973992>
> > > 
> > > .
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/paweldudek/mobile-warsaw-organization/issues/1#issuecomment-33976261
> .

## 

Cheers,

Wojtek Erbetowski
http://erbetowski.pl/

**Comment by pawelByszewski** [comment]
Czy tutaj przyda się jakaś pomoc organizacyjna? btw czy to dalej aktualne bo w tym wątku dawno postów nie były a i na meetup'ie niezbyt dużo osób się zapisało

**Comment by paweldudek** [comment]
Zapisy są otwarte od jakichś 2 h, nie panikowałbym. ;)

Z rzeczy, których nam brakuje to miejsce (mamy pomysł, ale brak odzewu. @wojtekerbetowski jaki jest tego status?) i sponsor (nad tym pracuję, mam jedną firmę, która jest chętna ale jeszcze nie zamknięta). 

No i kwestia kamery, Wojtek?

**Comment by potiuk** [comment]
Ja z nart więc z rzadka i mam wolny internet (ledwo co wystarcza na
publikowanie filmów z MCE ;). Ale z doświadczeń na poprzednich meetupów -
nie ma co panikować, ale warto wygenerować ruch.

1) Puśccie event na FB - trzeba zrobić Event z linkiem do biletów na
meetup-a (facebook ma taki ficzur), to zawsze dawało duży ruch: ludziom się
pojawiało w streamie FB. Meetup jest z rzadka aktywnie obserwowany przez
ludzi. Koniecznie trzeba dać ewentowi obrazek meetup-a z MW (kojarzy się
ludziom i jest lepiej widoczny w streamie). Dodatkowo każda osoba zapisana
na event może się pojawić jego znajomym w timelinie. Same plusy.

2) Podobnie Twitter i ewentualnie G+ (ale tam nie eventy tylko linki do
meetup-a). Generalnie spamowanie w wielu mediach równolegle jest OK, nie
kosztuje zbyt wiele. Warto podchodzić indywidualnie do każdego medium - na
FB event,  w twitterze bardzo krótka zajawka + link do meetup-a, na G+
trochę dłuższy opis + customowy obrazek + link do meetup-a. Koniecznie na
twitterze musi być zajawka tłumacząca co i jak, a nie sam link.

3) Można jeszcze kontrolnie i równolegle wysłać maila do wszystkich na
meetup-ie (powiedzieć że gość specjalny Saul Mora itd. itp.) - meetup
oczywiście sam spamuje ludzi mailami, ale one trochę giną w natłoku (są
zawsze takie same i ludzie ich nie czytają). To dużo lepiej wygląda jak
jest indywidualna wiadomość od organizatorów.

Napiszcie, czy potrzeba jakichś praw/adminów etc.

J.

+48 660 796 129
 Mobile Central Europe http://mobilecentraleurope.com/
"Humanity has advanced, when it has advanced, not because it has been
sober,
responsible, and cautious, but because it has been playful, rebellious, and
immature."

2014-02-17 20:54 GMT+01:00 Pawel Dudek notifications@github.com:

**Comment by pawelByszewski** [comment]
Jeśli ktoś z dostępem do tych kont puści inicjalny tweet etc. to nie da proszę znać - może ten 'post' umknąć w nawale informacji a chyba dobrze by było retweetować tweet wystawiony z konta MW niż, kazdy z osobna będzie pisał własną wersję. Analogicznie na innych portalach społecznościowych.

**Comment by potiuk** [comment]
+1 dokładnie tak robiliśmy do tej pory :)

J.

+48 660 796 129
 Mobile Central Europe http://mobilecentraleurope.com/
"Humanity has advanced, when it has advanced, not because it has been
sober,
responsible, and cautious, but because it has been playful, rebellious, and
immature."

2014-02-17 21:31 GMT+01:00 pawelByszewski notifications@github.com:

**Comment by paweldudek** [comment]
Ja mogê wrzuciæ jutro ofensywê medialn±. Potrzebowaæ bêdê dostêpu do G+ i
Twittera. Resztê mam.

W dniu 17 lutego 2014 21:54 u¿ytkownik Jarek Potiuk <
notifications@github.com> napisa³:

**Comment by wojtekerbetowski** [comment]
Jarku, chyba tylko Ty masz twittera MW, podzielisz się na lastpass?

On Mon, Feb 17, 2014 at 10:14 PM, Pawel Dudek notifications@github.comwrote:

> Ja mogê wrzuciæ jutro ofensywê medialn±. Potrzebowaæ bêdê dostêpu do G+ i
> Twittera. Resztê mam.
> 
> W dniu 17 lutego 2014 21:54 u¿ytkownik Jarek Potiuk <
> notifications@github.com> napisa³:
> 
> > +1 dok³adnie tak robili¶my do tej pory :)
> > 
> > J.
> > 
> > +48 660 796 129
> > Mobile Central Europe http://mobilecentraleurope.com/
> > "Humanity has advanced, when it has advanced, not because it has been
> > sober,
> > responsible, and cautious, but because it has been playful, rebellious,
> > and
> > immature."
> > 
> > 2014-02-17 21:31 GMT+01:00 pawelByszewski notifications@github.com:
> > 
> > > Je¶li kto¶ z dostêpem do tych kont pu¶ci inicjalny tweet etc. to nie
> > > da
> > > proszê znaæ - mo¿e ten 'post' umkn±æ w nawale informacji a chyba
> > > dobrze
> > > by
> > > by³o retweetowaæ tweet wystawiony z konta MW ni¿, kazdy z osobna
> > > bêdzie
> > > pisa³ w³asn± wersjê. Analogicznie na innych portalach
> > > spo³eczno¶ciowych.
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/paweldudek/mobile-warsaw-organization/issues/1#issuecomment-35320021>
> > 
> > > .
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/paweldudek/mobile-warsaw-organization/issues/1#issuecomment-35321928>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/paweldudek/mobile-warsaw-organization/issues/1#issuecomment-35323478
> .

## 

Cheers,

Wojtek Erbetowski
http://erbetowski.pl/

**Comment by wojtekerbetowski** [comment]
Podobnie z Page na G+

On Tue, Feb 18, 2014 at 10:21 AM, Wojtek Erbetowski wojtek@erbetowski.plwrote:

> Jarku, chyba tylko Ty masz twittera MW, podzielisz się na lastpass?
> 
> On Mon, Feb 17, 2014 at 10:14 PM, Pawel Dudek notifications@github.comwrote:
> 
> > Ja mogê wrzuciæ jutro ofensywê medialn±. Potrzebowaæ bêdê dostêpu do G+ i
> > Twittera. Resztê mam.
> > 
> > W dniu 17 lutego 2014 21:54 u¿ytkownik Jarek Potiuk <
> > notifications@github.com> napisa³:
> > 
> > > +1 dok³adnie tak robili¶my do tej pory :)
> > > 
> > > J.
> > > 
> > > +48 660 796 129
> > > Mobile Central Europe http://mobilecentraleurope.com/
> > > "Humanity has advanced, when it has advanced, not because it has been
> > > sober,
> > > responsible, and cautious, but because it has been playful, rebellious,
> > > and
> > > immature."
> > > 
> > > 2014-02-17 21:31 GMT+01:00 pawelByszewski notifications@github.com:
> > > 
> > > > Je¶li kto¶ z dostêpem do tych kont pu¶ci inicjalny tweet etc. to nie
> > > > da
> > > > proszê znaæ - mo¿e ten 'post' umkn±æ w nawale informacji a chyba
> > > > dobrze
> > > > by
> > > > by³o retweetowaæ tweet wystawiony z konta MW ni¿, kazdy z osobna
> > > > bêdzie
> > > > pisa³ w³asn± wersjê. Analogicznie na innych portalach
> > > > spo³eczno¶ciowych.
> > > > 
> > > > ## 
> > > > 
> > > > Reply to this email directly or view it on GitHub<
> > > 
> > > https://github.com/paweldudek/mobile-warsaw-organization/issues/1#issuecomment-35320021>
> > > 
> > > > .
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/paweldudek/mobile-warsaw-organization/issues/1#issuecomment-35321928>
> > > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/paweldudek/mobile-warsaw-organization/issues/1#issuecomment-35323478
> > .
> 
> ## 
> 
> Cheers,
> 
> Wojtek Erbetowski
> http://erbetowski.pl/

## 

Cheers,

Wojtek Erbetowski
http://erbetowski.pl/

**Comment by paweldudek** [comment]
Ja nie mam dostępu do LastPass :P

2014-02-18 10:24 GMT+01:00 Wojciech Erbetowski notifications@github.com:

> Podobnie z Page na G+
>

**Comment by wojtekerbetowski** [comment]
Załóż konto na tym mailu, tyle wystarczy, żeby Jarek mógł się podzielić :-)

2014-02-18 10:26 GMT+01:00 Pawel Dudek notifications@github.com:

> Ja nie mam dostępu do LastPass :P
> 
> 2014-02-18 10:24 GMT+01:00 Wojciech Erbetowski notifications@github.com:
> 
> > Podobnie z Page na G+
> > 
> > On Tue, Feb 18, 2014 at 10:21 AM, Wojtek Erbetowski <
> > wojtek@erbetowski.pl>wrote:
> > 
> > > Jarku, chyba tylko Ty masz twittera MW, podzielisz się na lastpass?
> > > 
> > > On Mon, Feb 17, 2014 at 10:14 PM, Pawel Dudek <
> > > notifications@github.com>wrote:
> > > 
> > > > Ja mogê wrzuciæ jutro ofensywê medialn±. Potrzebowaæ bêdê dostêpu do
> > > > G+
> > > > i
> > > > Twittera. Resztê mam.
> > > > 
> > > > W dniu 17 lutego 2014 21:54 u¿ytkownik Jarek Potiuk <
> > > > notifications@github.com> napisa³:
> > > > 
> > > > > +1 dok³adnie tak robili¶my do tej pory :)
> > > > > 
> > > > > J.
> > > > > 
> > > > > +48 660 796 129
> > > > > Mobile Central Europe http://mobilecentraleurope.com/
> > > > > "Humanity has advanced, when it has advanced, not because it has
> > > > > been
> > > > > sober,
> > > > > responsible, and cautious, but because it has been playful,
> > > > > rebellious,
> > > > > and
> > > > > immature."
> > > > > 
> > > > > 2014-02-17 21:31 GMT+01:00 pawelByszewski notifications@github.com:
> > > > > 
> > > > > > Je¶li kto¶ z dostêpem do tych kont pu¶ci inicjalny tweet etc. to
> > > > > > nie
> > > > > > da
> > > > > > proszê znaæ - mo¿e ten 'post' umkn±æ w nawale informacji a chyba
> > > > > > dobrze
> > > > > > by
> > > > > > by³o retweetowaæ tweet wystawiony z konta MW ni¿, kazdy z osobna
> > > > > > bêdzie
> > > > > > pisa³ w³asn± wersjê. Analogicznie na innych portalach
> > > > > > spo³eczno¶ciowych.
> > > > > > 
> > > > > > ## 
> > > > > > 
> > > > > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/paweldudek/mobile-warsaw-organization/issues/1#issuecomment-35320021>
> > 
> > > > > > .
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/paweldudek/mobile-warsaw-organization/issues/1#issuecomment-35321928>
> > 
> > > > > .
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/paweldudek/mobile-warsaw-organization/issues/1#issuecomment-35323478>
> > 
> > > > .
> > > 
> > > ## 
> > > 
> > > Cheers,
> > > 
> > > Wojtek Erbetowski
> > > http://erbetowski.pl/
> > 
> > ## 
> > 
> > Cheers,
> > 
> > Wojtek Erbetowski
> > http://erbetowski.pl/
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/paweldudek/mobile-warsaw-organization/issues/1#issuecomment-35366008>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/paweldudek/mobile-warsaw-organization/issues/1#issuecomment-35366229
> .

## 

Cheers,

Wojtek Erbetowski
http://erbetowski.pl/

**Comment by wojtekerbetowski** [comment]
Powiększenie odpadło. @spherefoundry będziesz próbował kosmoskosmos?

**Comment by pawelByszewski** [comment]
jeśli brakowało by rąk aby gdzieś zadzwonić to dajcie znać

**Comment by paweldudek** [comment]
Za³o¿y³em to konto. @Jarek dodasz mi tam co potrzeba?

2014-02-18 23:44 GMT+01:00 pawelByszewski notifications@github.com:

**Comment by potiuk** [comment]
Jaki adres? LastPass powiedział mi że pawel@dudek.mobi nie ma włączonej
opcji akceptowania "shareów".

+48 660 796 129
 Mobile Central Europe http://mobilecentraleurope.com/
"Humanity has advanced, when it has advanced, not because it has been
sober,
responsible, and cautious, but because it has been playful, rebellious, and
immature."

2014-02-19 20:40 GMT+01:00 Pawel Dudek notifications@github.com:

**Comment by paweldudek** [comment]
To ja chyba za głupi jestem na to :( Gdzie się włącza tą opcję? ;)

2014-02-19 23:26 GMT+01:00 Jarek Potiuk notifications@github.com:

**Comment by paweldudek** [comment]
Ok, coś poklikałem i coś się wygenerowało. Try now.

**Comment by potiuk** [comment]
Napisz mi co mam napisać ;) w poniedziałek to rozwiążemy :)

**Comment by paweldudek** [comment]
@wojtekerbetowski jak stoimy z kamerą?

**Comment by wojtekerbetowski** [comment]
Mam kamerê, Micha³ Lewandowski we¼mie statyw.
Jarku, mnie te¿ dodasz do Twittera?

On Fri, Feb 21, 2014 at 9:18 AM, Pawel Dudek notifications@github.comwrote:

> @wojtekerbetowski https://github.com/wojtekerbetowski jak stoimy z
> kamer±?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/paweldudek/mobile-warsaw-organization/issues/1#issuecomment-35707414
> .

## 

Cheers,

Wojtek Erbetowski
http://erbetowski.pl/

**Comment by potiuk** [comment]
Jak będę przy kompie w pn dodam was wszystkich :). Teraz jestem na wyciągu
i mogę napisać co trzeba. Dajcie do copypaste

**Comment by potiuk** [comment]
Zretweetowalem Wojtka. Wystarczy chyba :)

**Comment by paweldudek** [comment]
Wygląda na to, że wszystko ogarnięte. Zamykam zatem ticketa!

**Comment by potiuk** [comment]
Teraz już tak. Wysharowałem Tobie i Wojtkowi.

+48 660 796 129
 Mobile Central Europe http://mobilecentraleurope.com/
"Humanity has advanced, when it has advanced, not because it has been
sober,
responsible, and cautious, but because it has been playful, rebellious, and
immature."

**Comment by paweldudek** [comment]
Thx!

2014-02-23 20:56 GMT+01:00 Jarek Potiuk notifications@github.com:

> Teraz ju¿ tak. Wysharowa³em Tobie i Wojtkowi.
> 
> +48 660 796 129
> Mobile Central Europe http://mobilecentraleurope.com/
> "Humanity has advanced, when it has advanced, not because it has been
> sober,
> responsible, and cautious, but because it has been playful, rebellious,
> and
> immature."
>
