### ISSUE TITLE
Crossweb promotion

### ISSUE THREAD

**Issue by paweldudek** [paweldudek/mobile-warsaw-organization#11]
Gadaliśmy o tym na MetaMeetupie - ktoś coś wie, czy była podjęta próba kontaktu z Crosswebem?

**Comment by paweldudek** [comment]
Ok, widzę, że już ogarnięte to jest na meta meetup, my bad. Zamykam.

**Comment by wojtekerbetowski** [comment]
Spoko, zapodałem jakiś czas temu im info, że istniejemy :)
