### ISSUE TITLE
Merchandise

### ISSUE THREAD

**Issue by paweldudek** [paweldudek/mobile-warsaw-organization#13]
Szybko rzucam pomysł - może zrobilibyśmy merchandise Mobile Warsaw? Zacząć można banalnie, od koszulek. 

Chyba, że już to mamy. ;)

**Comment by wojtekerbetowski** [comment]
+1 jeden. Koszulki strasznie banalne, damy radê lepiej! :-)

2014-02-18 15:46 GMT+01:00 Pawel Dudek notifications@github.com:

> Szybko rzucam pomys³ - mo¿e zrobiliby¶my merchandise Mobile Warsaw? Zacz±æ
> mo¿na banalnie, od koszulek.
> 
> Chyba, ¿e ju¿ to mamy. ;)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/paweldudek/mobile-warsaw-organization/issues/13
> .

## 

Cheers,

Wojtek Erbetowski
http://erbetowski.pl/

**Comment by potiuk** [comment]
Koniecznie! Może jeszcze zróbmy taki merchandising żeby było MCE/MW
awers/rewers - jak na razie cross-promocja tylko obu wydarzeniom robi
dobrze.

Można by wtedy koszty merchandisingu pokryć z budżetu MCE. Tylko faktycznie
musi być coś odlotowego.. Wojtku - może pogadaj z dziewczynami i one coś
wymyślą. IMHO - musi być coś użytecznego (tak jak rękawiczki na MCE) tak
żeby każdy zapamiętał i może nawet przez jakiś czas używał. Kubek taki jest
ale podobnie jak koszulka jest banalny, chyba że coś ciekawego się wymyśli
w kontekście pół MCE/pół MW....

J.

*Jarek Potiuk, *CTO
*Polidea
http://www.polidea.pl/en/#utm_source=Email_Sig&utm_medium=email&utm_campaign=Email,
*
 Mobile Central Europe http://mobilecentraleurope.com/
Mobile: +48 660 796 129

2014-02-19 14:00 GMT+01:00 Wojciech Erbetowski notifications@github.com:

**Comment by paweldudek** [comment]
Nie, błagam, nie więcej kubków :(

Poza tym, zgadzam się z tym, że to powinno być coś użytecznego. Pomyślę nad
czymś sensownym. ;)

W dniu 19 lutego 2014 18:52 użytkownik Jarek Potiuk <
notifications@github.com> napisał:
