### ISSUE TITLE
June Meetup

### ISSUE THREAD

**Issue by paweldudek** [paweldudek/mobile-warsaw-organization#14]
- Prelegenci
  - Krzysztof Zabłocki
    - [x] Bio
    - [x] Streszczenie
    - [x] Fota
  - Karol Żak
    - [x] Bio
    - [x] Streszczenie
    - [x] Fota
  - Emilia Maj
    - [x] Bio
    - [x] Streszczenie
    - [x] Fota
- Venue
  - [x] Wybrane:
  - [x] Zaklepany termin:
  - [x] Opłacone
  - [x] Faktura przekazana do księgowości
- Info na społecznościach
  - [x] Twitter
  - [x] Mobile-warsaw.pl
  - [x] Facebook
  - [ ] G+
- [ ] Plakaty
- [x] Przypinki
- Sponsor
  - [x] Znaleziony:
  - [x] Faktura wystawiona
  - [x] Płatność przyszła
  - [x] Podziękowanie
- Kto ogarnia na miejscu:
- [ ] Kamera załatwiona
- [x] Spotkanie opublikowane

**Comment by paweldudek** [comment]
Emilia Maj nie da rady w maju i chciałaby w czerwcu. Damy radę zrobić w tym terminie spotkanie z 3 prelegentami? @wojtekerbetowski @potiuk @spherefoundry

**Comment by potiuk** [comment]
Ja nie mam nic naprzeciwko :)

+48 660 796 129
 Mobile Central Europe http://mobilecentraleurope.com/
"Humanity has advanced, when it has advanced, not because it has been
sober,
responsible, and cautious, but because it has been playful, rebellious, and
immature."

2014-04-14 11:27 GMT-07:00 Pawel Dudek notifications@github.com:

**Comment by wojtekerbetowski** [comment]
Pewnie, ju¿ w kwietniu tak robimy :)

On Tue, Apr 15, 2014 at 2:29 AM, Jarek Potiuk notifications@github.comwrote:

> Ja nie mam nic naprzeciwko :)
> 
> +48 660 796 129
> Mobile Central Europe http://mobilecentraleurope.com/
> "Humanity has advanced, when it has advanced, not because it has been
> sober,
> responsible, and cautious, but because it has been playful, rebellious,
> and
> immature."
> 
> 2014-04-14 11:27 GMT-07:00 Pawel Dudek notifications@github.com:
> 
> > Emilia Maj nie da rady w maju i chcia³aby w czerwcu. Damy radê zrobiæ w
> > tym terminie spotkanie z 3 prelegentami? @wojtekerbetowski<
> > https://github.com/wojtekerbetowski>
> > @potiuk https://github.com/potiuk @spherefoundry<
> > https://github.com/spherefoundry>
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/paweldudek/mobile-warsaw-organization/issues/14#issuecomment-40400869>
> > 
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/paweldudek/mobile-warsaw-organization/issues/14#issuecomment-40433681
> .

## 

Cheers,

Wojtek Erbetowski
http://erbetowski.pl/
