### ISSUE TITLE
July Meetup

### ISSUE THREAD

**Issue by paweldudek** [paweldudek/mobile-warsaw-organization#16]
Termin: 21 lipca.
- Prelegenci
  - Maciej Górski
    - [ ] Bio
    - [ ] Streszczenie
    - [ ] Fota
  - Rudy
    - [ ] Bio
    - [ ] Streszczenie
    - [ ] Fota
- Venue
  - [ ] Wybrane:
  - [ ] Zaklepany termin:
  - [ ] Opłacone
  - [ ] Faktura przekazana do księgowości
- Info na społecznościach
  - [ ] Twitter
  - [ ] Mobile-warsaw.pl
  - [ ] Facebook
  - [ ] G+
- [ ] Plakaty
- [ ] Przypinki
- Sponsor
  - [ ] Znaleziony:
  - [ ] Faktura wystawiona
  - [ ] Płatność przyszła
  - [ ] Podziękowanie
- Kto ogarnia na miejscu:
- [ ] Kamera załatwiona
- [ ] Spotkanie opublikowane

**Comment by paweldudek** [comment]
@spherefoundry proponuję w tym terminie wyjść na plażę.

**Comment by spherefoundry** [comment]
Mały update: prawie na 100% robimy w Macoscopie.
