### ISSUE TITLE
August Meetup

### ISSUE THREAD

**Issue by paweldudek** [paweldudek/mobile-warsaw-organization#17]
Termin: 25 sierpnia.
- Prelegenci
  - Ash Furrow
    - [x] Bio
    - [x] Streszczenie
    - [x] Fota
  - Robb Bohnke
    - [x] Bio
    - [x] Streszczenie
    - [x] Fota
- Venue
  - [x] Wybrane:
  - [x] Zaklepany termin:
  - [x] Opłacone
  - [x] Faktura przekazana do księgowości
- Info na społecznościach
  - [ ] Twitter
  - [ ] Mobile-warsaw.pl
  - [ ] Facebook
  - [ ] G+
- [ ] Plakaty
- [ ] Przypinki
- Sponsor
  - [x] Znaleziony:
  - [ ] Faktura wystawiona
  - [ ] Płatność przyszła
  - [ ] Podziękowanie
- Kto ogarnia na miejscu:
- [ ] Kamera załatwiona
- [ ] Spotkanie opublikowane

**Comment by paweldudek** [comment]
Disclaimer: ja przez pierwszą połowę sierpnia będę niedostępny (wakacje). Ktoś będzie musiał wziąć na klatę organizację w tym okresie. ;)

**Comment by wojtekerbetowski** [comment]
Ja nic w tym czasie nie planuję

**Comment by potiuk** [comment]
Ja raczej też nie (ale jak wiecie u mnie wtorkowy wyjazd do USA może być
zaklepany w poniedziałek). Więc wstępnie chętnie pomogę.

J.

*Jarek Potiuk, *CTO
*Polidea
http://www.polidea.pl/en/#utm_source=Email_Sig&utm_medium=email&utm_campaign=Email,
*
 Mobile Central Europe http://mobilecentraleurope.com/
Mobile: +48 660 796 129

**Comment by paweldudek** [comment]
Ash Furrow potwierdzony. :]

**Comment by pawelByszewski** [comment]
mnie nie ma przez 2 ostatnie tygodnie lipca, ale 2-go sierpnia wracam i mogę zabrać się do roboty.

**Comment by paweldudek** [comment]
Zaktualizowałem termin na 25.

**Comment by paweldudek** [comment]
Faktury opłacone, kasa przysła, wsio OK :)
