### ISSUE TITLE
May TDD Android workshop

### ISSUE THREAD

**Issue by pawelByszewski** [paweldudek/mobile-warsaw-organization#18]
Powoli czas do warsztatów się zbliża. Zmoderowałem odrobinę dyskusję wśród prowadzących i jakaś tam wspólny plan się skrystalizował zatem od strony merytorycznej sytuacja jest opanowana.

A co do spraw organizacyjnych.
@paweldudek jeśłi Twoja oferta z prywatnym repo na githubie jest dalej aktualna to byśmy poprosili o takie.

Jak wygląda sprawa z miejscem warsztatów, czy takie samo jak w przypadku iOS jest prawdopodobne? @paweldudek będizesz się tym zajmował czy mam to wziąć na siebie? jesli tak to jakaś mała pomoc będize mi pewnie potrzebna (choćby informacyjna)

Czy Allegro zdecydowało się zostać sponsorem imprezy?

**Comment by wojtekerbetowski** [comment]
Jeśli Allegro nie ma w końcu salki to spoko, bo mam jedną (GammaFactory)
i jest spora szansa, że się uda. Lecz potrzeba nam sponsora. Byłoby super dopiąć Allegro.

**Comment by wojtekerbetowski** [comment]
Czy mamy już datę? 10 maj to za wcześnie?

**Comment by pawelByszewski** [comment]
Merytorycznie na 10 maja się wyrobimy i tena termin wszysktim mentorom pasował.
A to czyły się jescze jakieś rozmowy z Pawłem Klimiukiem i jeśli tak to na czym stanęło. Ostatnio jestem dosyć blisko z Allegro więc mogę od środka trochę nadać tempa dyskusji.

**Comment by wojtekerbetowski** [comment]
OK, to postaraj się namówić Allegro na 1200-1500 zł sponsoringu. Dzięki
temu będziemy mieli salę, pizzę i napoje.

W takim razie ten termin bierzmy. Jeśli z Allegro się nie uda, to poszukamy
innego sponsora,
choć naprawdę trzymam kciuki.

Czy założysz na meetup to spotkanie (z jeszcze zamkniętą rejestracją)?

**Comment by pawelByszewski** [comment]
nie mam na meetupie żadnych możlwości na koncie MW

z batalią sponsoringową ruszę od wtorku/środy

**Comment by wojtekerbetowski** [comment]
Już powinieneś mieć. Potwierdź proszę.

**Comment by pawelByszewski** [comment]
Mam i spotkanie założę.

**Comment by paweldudek** [comment]
@pawelByszewski oferta dalej aktualna, prześlij mi mailem namiary na ludzi, którzy powinni mieć do tego dostęp. 

Jeśli chodzi o organizację miejscówki: byłoby idealnie, gdyby dało się zrobić gdzieś u Allegro. Jeśli nie: @wojtekerbetowski może spróbować załatwić miejsce na MIM UW. Miejsce fajne, ale zaplecze gastronomiczne dookoła kiepskie. 

Jeśli chodzi o innego sponsora: martwmy się, jak Allegro odmówi ;)

Thoughts? ;)

**Comment by pawelByszewski** [comment]
@wojtekerbetowski @paweldudek  jak myślicie, czy uda nam się załatwić salkę tak aby Allegro tylko wyłożyło pieniądze? Jeśli allegro miało by wynająć salkę to wtedy już raczej nie dołoży się na jedzenie + picie i będzie to oznaczało, że problem funduszy nie jest do końca rozwiązany.
A potrzebuję w miarę krótkim czasie deklaracji z naszej strony czy bardziej potrzebne nam są pieniądze czy bardziej potrzebna sala.

**Comment by wojtekerbetowski** [comment]
Tak, załatwimy salę. Pewnie w GammaFactory dam radę.

**Comment by paweldudek** [comment]
+1 na GammaFactory. Wojtku potrzebujesz pomocy z tym?

**Comment by wojtekerbetowski** [comment]
Jest tam 9 sporych stołów, ok 70 krzeseł. Jeśli trzeba czegpś więcej,
musimy zamówić.

Rzutnik i WiFi będzie, nie trzeba załatwiać.

Czego jeszcze trzeba? Załatwiać termin?

**Comment by wojtekerbetowski** [comment]
Wysłałem zapytanie do GF. Postaram się dziś klepnąć lokal.
