### ISSUE TITLE
March Meetup

### ISSUE THREAD

**Issue by paweldudek** [paweldudek/mobile-warsaw-organization#2]
- [x] Speakers
- [x] Venue
- [x] Sponsor
- [x] Updated website

Speaking: 
- Chris Eidhof
- Sebastian Suchanowski

Date: 18th March 2014. 

Potential sponsors: Macoscope

Venue: Powiększenie

**Comment by paweldudek** [comment]
Chris Eidhof będzie speakerem, właśnie go potwierdziłem. @potiuk @wolanski @wojtekerbetowski @spherefoundry pomysł na nie-iOS'owego speakera w tym terminie? ;)

**Comment by wojtekerbetowski** [comment]
OK, nie mam na ten moment pomysłu, ale myślę, że [Rudy](https://github.com/pjakubczyk) mógłby pokazać nowego [RoboSpocka](https://github.com/Polidea/RoboSpock)?

**Comment by potiuk** [comment]
A może też Marcin Korniluk o czymś co robił w uTeście - tam jakaś magia szła...

**Comment by potiuk** [comment]
Zagadam Marcina.

**Comment by paweldudek** [comment]
Sebastian Suchanowski chciałby też pogadać o Health2.0 Startups - IMO bardzo fajny i ciekawy temat, czegoś takiego jeszcze na MW nie było. Mówił też już o tym na MWoT, więc prezkę ma pewnie bardziej doszlifowaną ;)

**Comment by potiuk** [comment]
Dobry temat.

+48 660 796 129
 Mobile Central Europe http://mobilecentraleurope.com/
"Humanity has advanced, when it has advanced, not because it has been
sober,
responsible, and cautious, but because it has been playful, rebellious, and
immature."

2014-01-27 Pawel Dudek notifications@github.com

**Comment by paweldudek** [comment]
Jedyny problem, że z przykładami na iOS (tak wiem, specjalnie zostawiłem ten szczegół na potem ;) ).

**Comment by paweldudek** [comment]
Panowie, Panie, 

Co myślicie o Sebastianie? Ja dałbym go, moja jedyna wątpliwość jest taka, że mamy dużo iOS'a ostatnio. Z drugiej strony jego prezentacja jest (przynajmniej tak twierdzi) ogólna, z przykładami na iOS'ie, więc w sumie też będzie pasować...

Thoughts?

**Comment by potiuk** [comment]
Temat dobry jak pisałem - i chyba jednak dość ogólny. Więc spoko.

J.

+48 660 796 129
 Mobile Central Europe http://mobilecentraleurope.com/
"Humanity has advanced, when it has advanced, not because it has been
sober,
responsible, and cautious, but because it has been playful, rebellious, and
immature."

2014-01-28 Pawel Dudek notifications@github.com

**Comment by wojtekerbetowski** [comment]
+1 dla Sebastiana

**Comment by paweldudek** [comment]
Ok, zatem potwierdze Sebastianowi! 

Super, to znaczy, ze mamy speakerow dwa miesiące do przodu! Na kwiecień, maj i czerwiec po jednym juz. Mega :)

**Comment by potiuk** [comment]
Mega! Prawda!

+48 660 796 129
 Mobile Central Europe http://mobilecentraleurope.com/
"Humanity has advanced, when it has advanced, not because it has been
sober,
responsible, and cautious, but because it has been playful, rebellious, and
immature."

2014-02-03 Pawel Dudek notifications@github.com:

**Comment by wojtekerbetowski** [comment]
Powiększenie było zajęte w lutym, ale próbuję na marzec od razu dograć.

**Comment by wojtekerbetowski** [comment]
Mamy rezerwację w powiększeniu. 300zł netto za sprzęt audio musimy zapłacić.

**Comment by paweldudek** [comment]
Super. To (prawie) wszystko mamy załatwione. Trzeba tylko zamknąć sponsora (pomęczę Macoscope) i będziemy mieli całe spotkanie umówione. Super!

**Comment by paweldudek** [comment]
Ooo, właśnie, co mi się przypomniało. Co z plakatmi?

**Comment by paweldudek** [comment]
@wojtekerbetowski @potiuk @spherefoundry thoughts?

**Comment by pawelByszewski** [comment]
plakaty, to chodzi o projekt czy drukowanie? mam jedną niezbyt zaprzyjaźnioną ale znajomą firme zajmująca się drukiem, może udało by się załatwić jakieś zniżki w zamian za jakieś miejsce na reklamę.

**Comment by paweldudek** [comment]
Tj, mamy taką ideę: jeśli meetup na następny miesiąc mamy w miarę ogarnięty (a mamy... tak sądzę) to drukujemy plakaty na poprzedzającym spotkaniu i rozdajemy, coby sobie ludzie powiesili. W pracy. W domu. W toalecie. Wszędzie.

Póki co pytanie jest: czym mamy budżet, czy mamy czas i czy mamy projekt ;)

**Comment by pawelByszewski** [comment]
Dobrze by było mieć choćby projekt taki na A4/A3 to może uda się namówić zeby wydrykowali u siebie w pracy i powiesili, zawsze coś

**Comment by paweldudek** [comment]
Yup, ale o to musimy już poprosić Gosię z Polidei. ;) Zdalnie poprzez Jarka albo Wojtka.

**Comment by pawelByszewski** [comment]
Gosia jest "na etacie" od takich spraw? Bo jeśli nie ma czasu to mogę udeżyć do 2-3 osób czy nie chcę dla własnej satysfakcji przygotować jakiegoś projektu?

**Comment by paweldudek** [comment]
Gosia pomaga jak jest potrzeba/chwila czasu. Ale czy teraz może to musimy nam Jarek albo Wojtek powiedzieć ;)

**Comment by wojtekerbetowski** [comment]
Będę w poniedziałek, wtedy najwcześniej mogę się dowiedzieć.

2014-03-06 21:21 GMT+00:00 Pawel Dudek notifications@github.com:

> Gosia pomaga jak jest potrzeba/chwila czasu. Ale czy teraz może to musimy
> nam Jarek albo Wojtek powiedzieć ;)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/paweldudek/mobile-warsaw-organization/issues/2#issuecomment-36938543
> .

## 

Cheers,

Wojtek Erbetowski
http://erbetowski.pl/

**Comment by pawelByszewski** [comment]
znalazłem chętnego grafika z TouK, który możę zrobic jakiś projek.  Tylko pytanie czy na bazie kolorystyki itp. obecnej strony mobile/warsaw czy na podstwie tej nowej, o której dyskusja się toczy w innym issue?

**Comment by paweldudek** [comment]
Na następne spotkanie nie damy rady raczej zrobić plakatów, bo czasu mało i
nie mamy pełnego składu na spotkanie ;)

Ale! To jest świetne pytanie, jak robimy z szatą graficzną. Osobiście
byłbym za tym, by nową szatę graficzną ogarnąć wpierw, a potem bawić się w
plakat. Być może uda nam się popchnąć sprawę przed kwietniowym spotkaniem.
Majowe też już mamy częściowo zaplanowane, więc jest szansa, że do końca
kwietnia je całe dopniemy.

Thoughts?

W dniu 7 marca 2014 14:09 użytkownik pawelByszewski <
notifications@github.com> napisał:

**Comment by paweldudek** [comment]
Dyskusję o plakatach przeniosłem gdzie indziej. To spotkanie zasadniczo jest zamknięte, także zamykam też issue!
