### ISSUE TITLE
Mobile Warsaw & Cocoaheads Kraków Pub Quiz

### ISSUE THREAD

**Issue by siejkowski** [paweldudek/mobile-warsaw-organization#25]
### Prowadzący / przygotowanie pytań:
- Błażej Biesiada
- Michał Śmiałko
- Krzysztof Siejkowski
### Termin (prognoza):

9 października, 19:00 - 22:00
### Forma:

Quiz był mocno wzorowany na NSHipster Pub Quiz, aczkolwiek pytania były w 100% nasze i nieco łatwiejsze. Okazało się to strzałem w 10, zwycięski team miał około 60-70% poprawnych odpowiedzi i wszyscy dobrze się bawili :)
### Miejsce - wymagania:
- rzutnik/ekran do wyświetlania pytań
- kartki i długopisy
- nagłośnienie (jeśli są problemy z akustyką)
- dużo niewielkich stolików (żeby ludzie mogli się połączyć w małe grupy)
- scena/podwyższenie dla prowadzącego quiz
- centrum / dobry dojazd
- dobre piwo.
### Miejsce - pomysły:

Solec 44
### Limit uczestników:

40 osób, w porywach 50 osób
### Nastrój:

80 kuponów na piwo
### Nagroda:

50% zniżki na bilet MCE - do ustalenia
jakieś wirtualne - do decyzji
### Sponsor:

Taptera - 600 zł
Touk - 500 zł
### Partnerzy:
- Cocoaheads Kraków
- MCE

**Comment by paweldudek** [comment]
Odbyło się, skończyło się. Zamykam! :wink:
