### ISSUE TITLE
April Meetup

### ISSUE THREAD

**Issue by paweldudek** [paweldudek/mobile-warsaw-organization#4]
- [x] Speakers
- [x] Venue
- [x] Sponsor: Mobica
- [x] Website

Speaking:
- Dmytro
- Michał Tajchert

Nie mam jeszcze pomysłu, kogo tutaj. Ogólnie poprzednie meetupy będą bardziej iOS'owe, może postarajmy się zrobić go bardziej Androidowym?

**Comment by potiuk** [comment]
Po pierwsze zgadamy z Mateuszem. Może on coś podpowie.

A może zaprosimy do współpracy Wojtka Kalicinskiego z GDG? On może
sprowadzić trochę androidowych speakerów (ale może chcieć się promowac)?

Mogę z nimi pogadać.

J.

**Comment by wojtekerbetowski** [comment]
Bardzo dobry pomysł z Wojtkiem.

2014/1/26 Jarek Potiuk notifications@github.com

> Po pierwsze zgadamy z Mateuszem. Może on coś podpowie.
> 
> A może zaprosimy do współpracy Wojtka Kalicinskiego z GDG? On może
> sprowadzić trochę androidowych speakerów (ale może chcieć się promowac)?
> 
> Mogę z nimi pogadać.
> 
> J.
> On Jan 26, 2014 1:40 PM, "Pawel Dudek" notifications@github.com wrote:
> 
> > Nie mam jeszcze pomysłu, kogo tutaj. Ogólnie poprzednie meetupy będą
> > bardziej iOS'owe, może postarajmy się zrobić go bardziej Androidowym?
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/paweldudek/mobile-warsaw-organization/issues/4>
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/paweldudek/mobile-warsaw-organization/issues/4#issuecomment-33315916
> .

## 

Cheers,

Wojtek Erbetowski
http://erbetowski.pl/

**Comment by paweldudek** [comment]
Wojtku, napiszesz do niego? Zgadacie nas jakoś?

**Comment by wojtekerbetowski** [comment]
OK, napiszê.

On Sun, Jan 26, 2014 at 8:43 PM, Pawel Dudek notifications@github.comwrote:

> Wojtku, napiszesz do niego? Zgadacie nas jako¶?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/paweldudek/mobile-warsaw-organization/issues/4#issuecomment-33327738
> .

## 

Cheers,

Wojtek Erbetowski
http://erbetowski.pl/

**Comment by potiuk** [comment]
Super.

Ja zagadam Mateusza i jeszcze Dawida (Developer Relations) z Google'a - mam
też kontakt z Developer Relations z Pragi no i - mamy też kontakty do GDG
Lviw i GDG Minsk. Ja ich zagadam.

J.

+48 660 796 129
 Mobile Central Europe http://mobilecentraleurope.com/
"Humanity has advanced, when it has advanced, not because it has been
sober,
responsible, and cautious, but because it has been playful, rebellious, and
immature."

**Comment by potiuk** [comment]
Mam już wstępny pozytywny odzew z UK, BY i od Mateusza. Mateusz - jak tylko skończy - zbytnio - intensywny okres pracy przy obecnym projekcie, chętnie się chyba dołączy jako androidowy współorganizator MW - sam też jest chętny żeby opowiedzieć o portowaniu aplikacji Androidowych na Glassy, ale to wszystko na początku/w połowie lutego jak tylko się zmniejszy ciśnienie w tym co robi teraz.

**Comment by paweldudek** [comment]
Gites majonez. Zobaczmy, czy uda nam się ogarnąć dwóch speakerów androidowych - poprzednie spotkania będą bardziej general/ios, to spotkanie można zrobić bardziej android. 

Jarku, jeszcze jakieś info od grup GDG?

**Comment by potiuk** [comment]
Rozmawiamy jutro z Dmytro :).

+48 660 796 129
 Mobile Central Europe http://mobilecentraleurope.com/
"Humanity has advanced, when it has advanced, not because it has been
sober,
responsible, and cautious, but because it has been playful, rebellious, and
immature."

2014-01-28 Pawel Dudek notifications@github.com

**Comment by paweldudek** [comment]
@potiuk mamy jednego speakera, nie jestem pewien, co ustaliliśmy z drugim. @mgrzechocinski masz jakiś pomysł? ;)

**Comment by paweldudek** [comment]
@wojtekerbetowski @potiuk Czy 30 kwietnia (środa) to jest dobry pomysł? Zaraz po świętach. Chciałbym potwierdzić Dmitrowi.

**Comment by potiuk** [comment]
Dla mnie dobry jak każdy inny - poza tym że w środy mam Szlifa. Ale mogę go
ustawić tak, żeby był kto inny.

Ale może lepiej wtorek 29? 30 jest dokładnie tuż przed dłuugim weekendem...
Sporo ludzi będzie gdzieś w ten wieczór wybywała z Warszawy.

J.

+48 660 796 129
 Mobile Central Europe http://mobilecentraleurope.com/
"Humanity has advanced, when it has advanced, not because it has been
sober,
responsible, and cautious, but because it has been playful, rebellious, and
immature."

2014-03-21 17:08 GMT+01:00 Pawel Dudek notifications@github.com:

**Comment by paweldudek** [comment]
No to jasne, wszystkie znaki na niebie i na ziemi wskazują, że musi to być 29sty. ;)

**Comment by wojtekerbetowski** [comment]
A to teraz będziemy robili we wtorki? Może 28, poniedziałek?

**Comment by paweldudek** [comment]
A, pokiełbasiło mi się, myślałem, że w tamten weekend wypadają święta. Może
być i poniedziałek. Obiekcje coś ktoś? Odezwę się jeszcze do naszego
prelegenta czy pasuje mu też pon, wtorek już klepnął.

Pzdr,
P

2014-03-26 10:08 GMT+01:00 Wojciech Erbetowski notifications@github.com:

**Comment by wojtekerbetowski** [comment]
Robimy w GammaFactory. Ktoś wrzuci na stronę?

**Comment by paweldudek** [comment]
Wrzucone. @wojtekerbetowski @spherefoundry jak z piwem na miejscu? Jak załatwiamy nagrywanie?

**Comment by wojtekerbetowski** [comment]
Piwo musimy kupić w supermarkecie, nagrywanie też trzeba pożyczyć.
Pewnie wszystko na mojej głowie ;-)

On Tue, Apr 22, 2014 at 10:08 PM, Pawel Dudek notifications@github.comwrote:

> Wrzucone. @wojtekerbetowski https://github.com/wojtekerbetowski
> @spherefoundry https://github.com/spherefoundry jak z piwem na miejscu?
> Jak załatwiamy nagrywanie?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/paweldudek/mobile-warsaw-organization/issues/4#issuecomment-41089169
> .

## 

Cheers,

Wojtek Erbetowski
http://erbetowski.pl/

**Comment by pawelByszewski** [comment]
Mogę się zająć tym co jest Ci mniej na rękę lub jednym i drugim :)

**Comment by wojtekerbetowski** [comment]
Bardzo chętnie piwem (musisz pewnie kogoś do pomocy poprosić).
Jeśli chodzi o nagrywanie, to potrzeba wcześniej pojechać na MIMUW po
sprzęt.

Nie mamy też nagłośnienia :-( ale chyba już nie zdążę załatwić.

**Comment by pawelByszewski** [comment]
A jak wygląda sprawa ma wyglądać sprawa z ilością, rodzajem i ceną za piwo?

**Comment by wojtekerbetowski** [comment]
Na oko 120 sztuk po 3-4 PLN za butelkę. Brzmi dobrze? Rodzaje zwykle
możliwie mieszam

On Wed, Apr 23, 2014 at 10:59 PM, pawelByszewski
notifications@github.comwrote:

> A jak wygląda sprawa ma wyglądać sprawa z ilością, rodzajem i ceną za piwo?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/paweldudek/mobile-warsaw-organization/issues/4#issuecomment-41214031
> .

## 

Cheers,

Wojtek Erbetowski
http://erbetowski.pl/

**Comment by pawelByszewski** [comment]
a jeszcze w sprawach formalnych, czy na te piwo wziąc fakturę i jęśli tak to jakie dane. 
a w kwesti organizacyjnej podwiozę te piwo w jakieś 30 min, przed spotkaniem

**Comment by paweldudek** [comment]
Dane do fakturki:

MCE-MEETLAB Sp. z o.o.
Osowska 23/6
04-302 Warszawa
NIP 1132870945

30 min przed będzie ok, ja postaram się być na miejscu w tych okolicach
czasowych (aka 17:30).

W dniu 25 kwietnia 2014 08:35 użytkownik pawelByszewski <
notifications@github.com> napisał:

**Comment by wojtekerbetowski** [comment]
Czy mamy w końcu sponsora? Sorry za nieogarnięcie...

**Comment by paweldudek** [comment]
Jak to, nie załatwiliśmy sponsora? :O

A na serio to jest, Mobica płaci 1200 zł netto. Chill out, zająłem się tym ;)

**Comment by wojtekerbetowski** [comment]
Ufff, ulżyło mi :-) za dużo spraw naraz

**Comment by pawelByszewski** [comment]
Czy ten szlaban i wewnętrzy parking, który widać na google maps na hożej 51 to część GammaFactory? nie wiecie czy jest opcja aby tam wjechać aby było łatwiej piwo przetransportować? troche tego jest, a parkowanie na hożej to wielka loteria

**Comment by wojtekerbetowski** [comment]
Tak, zwykle można wjechać. Choć czasem ten gość robi problemy.
O której będziesz?

Kupiłeś już, czy będziesz kupował? Pomyślałem, że można by do 140
zwiększyć...

**Comment by pawelByszewski** [comment]
kupione juz 120, kupienie kolejnych 20 może być problematyczne ale przy odrobinie szczęścia powinno się udać

**Comment by wojtekerbetowski** [comment]
OK, to olej. Tyle to najwyżej w Carrefourze się weźmie :-)

**Comment by pawelByszewski** [comment]
Będe tak jak wspominałem, koło 17:30. -  to tak nawiżaując do pytania, na które nie odpowiedziałem :)
