### ISSUE TITLE
May Meetup

### ISSUE THREAD

**Issue by paweldudek** [paweldudek/mobile-warsaw-organization#5]
Speakers:
- Jo Overline
- Cukeriada

Date: 19th May.

Sponsor: Blade Polska

**Comment by paweldudek** [comment]
Wiem, że Jo jest iOS, ale w tym terminie Tom Maes chciał do nas przyjechać - chcemy zrobić kolejne bardziej iOS spotkanie? Czy próbować przebookować go na czerwiec?

**Comment by potiuk** [comment]
Zapytaj Tom-a... Może ma "luźniejsze plany". Albo można 2 spotkania zrobić
w maju ;) ... Jedno z Tomem, jedno z Jo. Ja bym tam się trzymał formuły
"osoba z zagranicy + osoba z Polski".

J,

*Jarek Potiuk, *CTO
*Polidea
http://www.polidea.pl/en/#utm_source=Email_Sig&utm_medium=email&utm_campaign=Email,
*
 Mobile Central Europe http://mobilecentraleurope.com/
Mobile: +48 660 796 129

2014-02-21 18:21 GMT+01:00 Pawel Dudek notifications@github.com:

**Comment by paweldudek** [comment]
Z Tomem się urwało, on ma takie "napady" na odpisywanie ;) Możemy założyć, że wpadnie w wakacje/po wakacjach.

Póki co wyklarowała nam się data: 19 maja. Może pomyślmy nad miejscem/drugim speakerem/sponsorem i załatwy plakaty na kwietniowe spotkanie? ;)

@spherefoundry Masz fajny pomysł na miejscówkę?
@pawelByszewski / @mgrzechocinski macie pomysł na Androidowego speakera? 

No i wszyscy - sponsor? ;)

**Comment by potiuk** [comment]
Mam dodatkową możliwość w Maju zorganizowania speakera z zagranicy. Co prawda nie IOS, tylko mobile web, ale może być naprawdę fajny:

Maximliano Firt (http://firt.mobi). On będzie na Atmosphere ( w kinie Praha) 19-20 maja a przy okazji będzie robił dzień wcześniej warsztaty. Mam mieć do niego kontakt a w zamian jest prośba o rozreklamowanie Atmosphere na naszych mediach społecznościowych. Znowu wychodzi nam 3 speakerów (w tym dwóch zagranicznych!) ale myślę, że warto w to wchodzić! 

J.

**Comment by paweldudek** [comment]
Myślę, że OK. Wolałbym android, ale grunt, że Mobile ;)

W dniu 1 maja 2014 11:11 użytkownik Jarek Potiuk
notifications@github.comnapisał:

**Comment by potiuk** [comment]
Dobra. To organizuję ;).

+48 660 796 129
 Mobile Central Europe http://mobilecentraleurope.com/
"Humanity has advanced, when it has advanced, not because it has been
sober,
responsible, and cautious, but because it has been playful, rebellious, and
immature."

2014-05-01 11:14 GMT+02:00 Pawel Dudek notifications@github.com:

**Comment by paweldudek** [comment]
Pozostaje kwestia ogarnięcia faktur i możemy zamykać. @spherefoundry daj znać jak będzie faktura za sprzątanie.

**Comment by wojtekerbetowski** [comment]
Zapłaciłem Sound. Coś jeszcze?

2014-05-20 19:49 GMT+02:00 Pawel Dudek notifications@github.com:

> Pozostaje kwestia ogarnięcia faktur i możemy zamykać. @spherefoundryhttps://github.com/spherefoundrydaj znać jak będzie faktura za sprzątanie.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/paweldudek/mobile-warsaw-organization/issues/5#issuecomment-43660014
> .

## 

Cheers,

Wojtek Erbetowski
http://erbetowski.pl/

**Comment by paweldudek** [comment]
Jeszcze za sprzątanie musimy zapłacić, @spherefoundry ma dostać fakturę.

**Comment by paweldudek** [comment]
@spherefoundry co z płatnością za to? Chciałbym zamknąć ;)

**Comment by spherefoundry** [comment]
@paweldudek już dawno ogarnięte.

**Comment by paweldudek** [comment]
Cool. To zamykam. Pozwolę sobie jeszcze tylko zapostować naszą wspólną fotę :D

![dsc_8756_small](https://cloud.githubusercontent.com/assets/968513/3497529/8b909328-05ec-11e4-94fd-e6bbbf1994db.jpg)
