### ISSUE TITLE
Website - ideas

### ISSUE THREAD

**Issue by paweldudek** [paweldudek/mobile-warsaw-organization#6]
Wiem, że niby inżynierskie działa - nie ruszaj, ale może jakieś pomysły jak lepiej/fajniej zrobić naszą stronkę wypłyną? ;)

**Comment by wojtekerbetowski** [comment]
Pewnie, że warto zmienić. Ta tymczasowa i tak długo się utrzymała.
Proponuję jednak naradzić się z kimś z designu (może z Polidei) i zrobić to
na Foundation/Bootstrap3.

Przydałaby się strona About i kilka informacji dla sponsorów, itp

2014/1/26 Pawel Dudek notifications@github.com

> Wiem, że niby inżynierskie działa - nie ruszaj, ale może jakieś pomysły
> jak lepiej/fajniej zrobić naszą stronkę wypłyną? ;)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/paweldudek/mobile-warsaw-organization/issues/6
> .

## 

Cheers,

Wojtek Erbetowski
http://erbetowski.pl/

**Comment by paweldudek** [comment]
O, byłoby super gdyby ktoś o większym pojęciu o designie mógł rzucić na to okiem ;)

**Comment by gregwolanski** [comment]
Ja chętnie przygotuję jakąś propozycję, natomiast super byłoby mieć treść
do "About" oraz "kilka informacji dla sponsorów" i "itp.". : )

— G.

**Comment by wojtekerbetowski** [comment]
OK to ogarnê w tygodniu komplet informacji :-)

2014/1/26 Gregory Wolanski notifications@github.com

> Ja chêtnie przygotujê jak±¶ propozycjê, natomiast super by³oby mieæ tre¶æ
> do "About" oraz "kilka informacji dla sponsorów" i "itp.". : )
> 
> -- G.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/paweldudek/mobile-warsaw-organization/issues/6#issuecomment-33318108
> .

## 

Cheers,

Wojtek Erbetowski
http://erbetowski.pl/

**Comment by gregwolanski** [comment]
Ping. :)

**Comment by wojtekerbetowski** [comment]
Ongoing :)

**Comment by wojtekerbetowski** [comment]
Informacje na nową stronę:

#### O grupie

Grupa Mobile Warsaw powstała w marcu 2013 roku i od początku ma na celu budowanie społeczności programistów technologii mobilnych. Okazją do spotkania i poznania innych programistów są comiesięczne spotkania MW. Formuła spotkań to [barcamp](https://en.wikipedia.org/wiki/BarCamp), czyli spotykamy się w barach przy piwie, zaczynamy od dwóch, około półgodzinnych technicznych prelekcji, a następnie kontynuujemy rozmowami kuluarowymi, czasem trwającymi do późnych godzin nocnych.

#### Współpraca

##### Dla innych inicjatyw

Budując społeczność w Warszawie staramy się pomagać innym inicjatywom, a także chętnie sami czerpiemy z wiedzy innych. Jeśli uważasz, że możemy i Tobie pomóc, skontaktuj się z nami.
Możesz promować swoją _darmową_ inicjatywę wśród członków MW, pod warunkiem, że tematyka jest choćby zbliżona do programowania mobile.
Jeśli chodzi o płatne inicjatywy, to wraz z reklamą chcemy, aby szła korzyść dla uczestników,
zwykle w postaci darmowego biletu do rozlosowania wśród uczestników.

##### Dla firm

Ponieważ panuje wielki głód na programistów mobilnych, firmy chcące dotrzeć do rozwijających się, ciekawych tematu osób są mile widziane na spotkaniach. Podobnie jak w przypadku innych inicjatyw zawsze staramy się, aby za korzyścią dla firmy szła także korzyść dla uczestników, zwykle w postaci darmowego piwa, nagrań spotkań umieszczonych online, czy wynajętego lokalu.
Jeśli chciał(a)byś, aby Twoja firma dotarła do członków MW napisz na [mobile-warsaw-organizers@googlegroups.com].

**Comment by wojtekerbetowski** [comment]
Trochę podstawowych info wrzuciłem, pewnie przyda się polinkować tu i ówdzie, może rozpisać się bardziej, ale to już zależy od planu strony.

**Comment by potiuk** [comment]
Jedna drobna propozycja ode mnie: na pewno trzeba zmienić
"Organizers/Organizatorzy" na "Founders/Założyciele". A jako
"Organizatorów" umieściłbym może (pytanie czy tego chcą) osoby faktycznie
zaangażowane w organizację.

To jest w ogóle oddzielna dyskusja którą musimy zakończyć przy okazji
zakładania fundacji, ale myślę, że w tym przypadku nie będzie żadnych
wątpliwości - oddaje to stan faktyczny.

J.

*Jarek Potiuk, *CTO
*Polidea
http://www.polidea.pl/en/#utm_source=Email_Sig&utm_medium=email&utm_campaign=Email,
*
 Mobile Central Europe http://mobilecentraleurope.com/
Mobile: +48 660 796 129

2014-02-07 Wojciech Erbetowski notifications@github.com:

**Comment by gregwolanski** [comment]
Panowie,

nie znamy się za bardzo i jestem nowy w Waszym gronie, w związku z czym wyłącznie nieśmiało suponuję kilka rzeczy związanych ze stroną. ;) :)

Poświęciłem jej (tj. stronie Mobile Warsaw) raptem jeden nie-długi wieczór. 

Pozwoliłem sobie nie ograniczać się do ingerencji w warstwę wizualną. Dostało się też architekturze informacji.

Rzecz jest bardzo work in progress. Miejscami to projekt-projekt, miejscami jeszcze makieta.

Będę zobowiązany za każdy feedback.

A, w związku z charakterem Mobile Warsaw myślę o rzeczy mobile first. Ufam, że nie będziecie mieli nic przeciwko.

Aktualnie ogółem wygląda to tak:
https://dl.dropboxusercontent.com/s/7joggph27qxxk9w/2014-02-14%20at%2000.41.png

Moja nieśmiała propozycja w wersji 0.0.0.0.1 beta:
https://dl.dropboxusercontent.com/s/wj1v53zv5alj479/2014-02-14%20at%2000.40.png

Co myślicie?

**Comment by wojtekerbetowski** [comment]
Hej,

Jak na 0.0.....1 to mi się bardzo podoba. Fajna kolorystyka, ale nie
potrafię sobie jeszcze tego wyobrazić w wersji desktop.
Co do treści - to dałbym jeszcze stroną 'o grupie' i tam bym wrzucił
organizers
i to bardziej jako osoby obecnie zaangażowane (i info, że założycielami
była ta trójka).
Na głównej stronie nie jest to najważniejsza informacja.

2014-02-14 0:47 GMT+01:00 Gregory Wolanski notifications@github.com:

> Panowie,
> 
> nie znamy się za bardzo i jestem nowy w Waszym gronie, w związku z czym
> wyłącznie nieśmiało suponuję kilka rzeczy związanych ze stroną. ;) :)
> 
> Poświęciłem jej (tj. stronie Mobile Warsaw) raptem jeden nie-długi
> wieczór.
> 
> Pozwoliłem sobie nie ograniczać się do ingerencji w warstwę wizualną.
> Dostało się też architekturze informacji.
> 
> Rzecz jest bardzo work in progress. Miejscami to projekt-projekt,
> miejscami jeszcze makieta.
> 
> Będę zobowiązany za każdy feedback.
> 
> A, w związku z charakterem Mobile Warsaw myślę o rzeczy mobile first.
> Ufam, że nie będziecie mieli nic przeciwko.
> 
> Aktualnie ogółem wygląda to tak:
> 
> https://dl.dropboxusercontent.com/s/7joggph27qxxk9w/2014-02-14%20at%2000.41.png
> 
> Moja nieśmiała propozycja w wersji 0.0.0.0.1 beta:
> 
> https://dl.dropboxusercontent.com/s/wj1v53zv5alj479/2014-02-14%20at%2000.40.png
> 
> Co myślicie?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/paweldudek/mobile-warsaw-organization/issues/6#issuecomment-35040871
> .

## 

Cheers,

Wojtek Erbetowski
http://erbetowski.pl/

**Comment by gregwolanski** [comment]
Dzięki.

Wdrożę uwagę o treści, dopracuję 0.0.0.0.1 betę w wersji smartfonicznej i zrobię pierwszą wprawkę do dużej wersji. :)

Uwagi i sugestie nieustannie mile widziane.

**Comment by wojtekerbetowski** [comment]
Mamy jeszcze spotkania wyjazdowe "on tour", czy masz jakiś pomysł jak je
wkomponować?

**Comment by gregwolanski** [comment]
Zajmę się tym. :)

**Comment by wojtekerbetowski** [comment]
Super :-)

**Comment by gregwolanski** [comment]
Cześć,

dopracowana wersja nie-wielka z rozwiniętym menu:

https://dl.dropboxusercontent.com/s/a4d3bsm6xmx74aj/2014-02-26%20at%2023.06%20%281%29.png

Większa wersja, z której nie jestem jakoś mega zadowolony:

https://dl.dropboxusercontent.com/s/84s92rm1x22l03n/2014-02-26%20at%2023.06.png

Będę nad tym jeszcze pracował. Pewnie w sobotę. Byłoby super dostać od Was do tego czasu feedback.

Ćwiczenia nad większą wersją "ujawniły" kilka kwestii.
- Dopiero dojrzałem, że na stronach part meetupów w dolnym prawym rogu pojawia się logo sponsora. Chcecie, żeby one było tak symboliczne?
- Widziałem kilka filmów z MW na YouTube. Fajnie byłoby zintegrować kanał ze stroną, hm?
- Zdjęcia. Dobrej jakości, wysokiej rozdzielczości zdjęcia z meetupów. Może mi ktoś dostarczyć? Użyłem foci z Facebooka.
- Font. Podoba Wam się?

Czy wersja mobile poza brakiem "integracji" YouTube'a i logo sponsora danego meetupu jest w porządku?

Pozdrawiam. :)

**Comment by gregwolanski** [comment]
Aż tak źle? :) Wystarczy słowo.

**Comment by wojtekerbetowski** [comment]
Hej,

Bardzo skrótowo, bo jestem na urlopie. Strona w większej wersji bardzo mi
się podoba.
Kilka odpowiedzi poniżej

>    -
> 
>    Dopiero dojrzałem, że na stronach part meetupów w dolnym prawym rogu
>    pojawia się logo sponsora. Chcecie, żeby one było tak symboliczne?
> 
> Dobrze, jakby gdzieś się znalazło dla nich miejsce (uwaga, może być więcej
> niż jeden).
> W końcu obiecujemy im to jak dogrywamy warunki
> 
>    -
> 
>    Widziałem kilka filmów z MW na YouTube. Fajnie byłoby zintegrować
>    kanał ze stroną, hm?
> 
> Bardzo fajnie, niestety nie mogę znaleźć metody łatwej migracji ;-( nie
> wiem czy nie trzeba będzie po prostu przekopiować i stracić historii
> 
>    -
> 
>    Zdjęcia. Dobrej jakości, wysokiej rozdzielczości zdjęcia z meetupów.
>    Może mi ktoś dostarczyć? Użyłem foci z Facebooka.
> 
> Zwykle foty robi netczuk.tomasz@gmail.com może ma oryginały?
> 
>    -
> 
>    Font. Podoba Wam się?
> 
>  Mi tak, ale ja się nie znam :-)

**Comment by gregwolanski** [comment]
Dzięki. :)

Napisałem już e-maila gdzie trzeba w temacie zdjęć.

**Comment by paweldudek** [comment]
Ufff, w końcu odkopałem więc może rzucę parę słów od siebie:

Wersja mobilna:
- Menu się chowa, prawda? :P
- To czerwone tło wciąż wydaje mi się mało czytelne. Tj czerwone tło + biały napis. Plus jeszcze jedna rzecz: bardzo podoba mi się aktualne zdjęcie na mobile warsaw w tle (widok na centrum Warszawy). Myślę, że to lepsza symbolika niż zdjęcie z meetupa (to możemy mieć w galerii)
- Brakuje sponsorów
- Poza tym idealnie :+1: 

Wersja desktop:
- Czerwone tło strikes back!
- Nie wiem, czy zrobienie tego w kolumnach nie jest pewną formą marnotrawienia przestrzeni. Z drugiej strony jest tak lekko. Hm. Pomyślałbym o tym tak: jaka jest najważniejsza informacja dla ludzi wchodzących na naszą stronę? (Nadchodzące spotkanie) Jaka jest, z naszego punktu widzenia, druga najważniejsza informacja na głównej stronie? IMO poprzednie spotkania lub partnerzy. Możemy zrobić hangout o tym i pogadać jak chcesz! Daj znać co sądzisz :)

Generalnie o pytaniach:
- Pomysł na galerię na stronie: kozacki! Let's do it. Pisałeś do Tomka? Odpisał Ci coś?
- Embedowane videos ze spotkań: jeszcze lepiej! 
- Koniecznie loga sponsorów, plus jak pisał Wojtek może być więcej niż jeden. 
- Font jest fajny. I like it. Co to?

**Comment by gregwolanski** [comment]
Dzięki.

Odpowiem po sobocie. :)

**Comment by wojtekerbetowski** [comment]
Tymczasem kilka sobót później :-)

Byłoby ekstra pociąć i odpalić stronę niedługo. Co Ty na to?

**Comment by gregwolanski** [comment]
A ja na to jak na lato.

Przepraszam za brak odzewu, ale przygniotła mnie praca i część rzeczy z to-do listy musiałem przenieść do podlisty "Zająć się tym dopiero jak mnie ktoś pingnie". Ping odebrany. Siedzę teraz w kawiarni i klikam taski z tym związane. Postaram się w tym tygodniu poświęcać temu 30-60 minut/dzień i do końca tygodnia jakoś dowieźć co trzeba.

**Comment by wojtekerbetowski** [comment]
Super, jeśli będziemy jakoś w stanie pomóc - daj znać. Jeśli będziesz
wrzucał na bieząco do brancha w repo
to istnieje spora szansa, że ktoś w wolnej chwili zrobi PR.

**Comment by gregwolanski** [comment]
Weekend się kończy, ja mam progress, ale do dowiezienia tego brakuje mi kilku-kilkunastu godzin.

ETA: Weekend majowy

Przepraszam.

Nie obrażę się, jeśli napiszecie mi w odpowiedzi "sory Wolański, nie dowozisz".

Dobrego tygodnia.

**Comment by wojtekerbetowski** [comment]
Spoko, mam podobnie. Weekend majowy - żona z dzieckiem wyjeżdża, a ja mam
czas na zaległości.

2014-04-21 20:31 GMT+02:00 Gregory Wolanski notifications@github.com:

> Weekend się kończy, ja mam progress, ale do dowiezienia tego brakuje mi
> kilku-kilkunastu godzin.
> 
> ETA: Weekend majowy
> 
> Przepraszam.
> 
> Nie obrażę się, jeśli napiszecie mi w odpowiedzi "sory Wolański, nie
> dowozisz".
> 
> Dobrego tygodnia.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/paweldudek/mobile-warsaw-organization/issues/6#issuecomment-40961703
> .

## 

Cheers,

Wojtek Erbetowski
http://erbetowski.pl/

**Comment by wojtekerbetowski** [comment]
Odgrzebuję. Udaje Ci się coś podziałać prze weekend?

**Comment by gregwolanski** [comment]
Nie dam rady. Majówka okazała się pracująco-pracująca. Potrzebuję snu. Przepraszam.

Fajnie było chociaż poklikać rzeczy z myślą o czymś tak fajnym jak Mobile Warsaw. Dzięki za możliwość i cierpliwość.

Mała inspiracja dla kogoś, kto dowozi: https://dl.dropboxusercontent.com/u/1289645/Mobile%20Warsaw.png (sporo lepiej wygląda to w przeglądarce niż z lotu ptaka)

Jeszcze w temacie pytań Pawła:
- Oczywko, że menu winno się chować (i tak było zaprojektowane).
- Tło jest ograniczenie czytelne, ale ta czerwień to najmocniejszy akcent identyfikacji wizualnej Mobile Warsaw.
- Aktualne zdjęcie Warszawy jest jak stockowe zdjęcie uśmiechniętych ludzi. Super, że macie zdjęcia Tomka Netczuka i IMO warto z nich korzystać.
- Apropos zdjęć Tomka: Zdjęcia na https://plus.google.com/photos/+TomaszNetczuk/albums są najlepszymi jakie ma. RAW-y kasuje po wrzuceniu zdjęć na G+.
- Font nazywa się Ruda. Polecam. Bardzo pasuje do Mobile Warsaw. :) https://www.google.com/fonts/specimen/Ruda

Jeszcze raz dzięki, jeszcze raz przepraszam. Nie będę Was już niepokoił. :]

**Comment by paweldudek** [comment]
Mały update: stroną zajmuje się teraz Maria z polecenia Pawła. Będę wrzucać info jak coś się zmieni.
