### ISSUE TITLE
Cocoa Kucha with Orta Therox

### ISSUE THREAD

**Issue by paweldudek** [paweldudek/mobile-warsaw-organization#8]
Niestety nie wiem, czy wypali w maju, Orta wspominał, że jedzie wypadła mu w tym terminie dodatkowa konferencja. We'll see.

**Comment by potiuk** [comment]
Oby wypaliło :)

**Comment by paweldudek** [comment]
Jak nie wtedy to pewnie w innym terminie. Nie wypuszczę tego z dłoni ;)
