### ISSUE TITLE
Mid-day/lunch meetups in companies

### ISSUE THREAD

**Issue by potiuk** [paweldudek/mobile-warsaw-organization#9]
Just a wild thought.....

I was a bit inspired by Appsterdam's Weekly Lunchtime sessions.

http://t.co/LyZa4LxTv4

Maybe we can try to do something similar (possibly not weekly - maybe approx. every month in-between MW events). We could ask various companies to host such lunchtime MW meet-ups? Hosting company would have to organise and provide pizza/sandwich lunch and speaker who could tell some technical details of what they are currently working on - this would be 1.5 hour event or so .... The company would tell how many people they can host and we would then make a meetup and limit number of people - and have some strict rules for non-shows.

Wild thought as I said, but might be worth doing - especially that we could pass the organisation to the companies and we would only announce it.

**Comment by paweldudek** [comment]
Please please please let's do this! 

My only concern is that there's not enough companies in Warsaw willing to host this so that we get a different each month... for at least a year.

**Comment by potiuk** [comment]
Learning from a number of companies that sent people to MCE - there are plenty :) 

Let's worry about it a year from now :).

Polidea can be one of the first companies, I am sure Taptera will be happy to do it, UpNext as well, we can have uTest hosting it as well (@Polidea by coincidence) and I can easily think of few more companies ....

J.

**Comment by paweldudek** [comment]
I believe there are plenty, I just worry that there won't be enough willing to host such a meeting. But!

Let's do this agile way: see if it works :P

I'm all in. I'd try to do the first meeting when it gets a bit warmer - people might be put off by low temperature right now.

**Comment by paweldudek** [comment]
Zrobiło się cieplej - ruszamy z tym?
